# Generated by Django 4.1 on 2022-08-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_category_options_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='tags',
            field=models.ManyToManyField(to='courses.tag'),
        ),
    ]
